Expbeaut:expbeaut.cpp tokenscanner.h tokenscanner.cpp tokenpatch.h strlib.h strlib.cpp error.h error.cpp stack.h vector.h foreach.h
	g++ -o Expbeaut -g expbeaut.cpp tokenscanner.h tokenscanner.cpp tokenpatch.h strlib.h strlib.cpp error.h error.cpp stack.h vector.h foreach.h

clean:
	rm Expbeaut
